#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    file="$1"
    ip="$2"
    user="$3"
    key="$4"
    scp -o "StrictHostKeyChecking=no" -i "$key" "$file" "$user@$ip":~/
fi
