#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to respect requirements

sudo apt update
sudo apt -y install nginx
sudo ufw app list
sudo ufw allow 'Nginx HTTP'

if [ ! -d /var/www/html ]; then
  sudo mkdir -p /var/www/html
fi

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

sudo service nginx start
