#!/usr/bin/env bash
# Installing and configuring HAProxy.
# Distributing requests using a roundrobin.
# Making sure that HAproxy can be managed via an init script

# Updating the system and installing HAProxy
sudo apt -y update
sudo apt install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt install haproxy=2.6.\*

# Configuring HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
frontend my_frontend_server
    bind *:80
    mode http
    default_backend my_backend_server

backend my_backend_server
		mode http
    balance roundrobin
    server 166734-web-01 34.229.189.80:80 check
    server 166734-web-02 18.204.11.87:80 check
EOF

# Enabling HAProxy via init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart HAProxy
sudo service haproxy restart
